FROM node:18-alpine

WORKDIR /app

RUN addgroup -g 1001 -S nodejs && \
    adduser -S nodejs -u 1001

COPY package*.json ./
RUN npm install

COPY . .

RUN chown -R nodejs:nodejs /app
USER nodejs

EXPOSE 3000 9229

CMD ["npm", "run", "dev"]